name: Building, linting
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
   branches: [main]
  pull_request:
    branches: [main, dev]
jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [17.4.0]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Building prod project
        run: npm run build:prod
        if: always()
      - name: Run ESLint
        run: npm run lint:ts
        if: always()
      - name: Run StyleLint
        run: npm run lint:scss
        if: always()
      - name: Run Unit Tests
        run: npm run test:unit
        if: always()
      - name: Run StoryBook build
        run: npm run storybook:build
        if: always()
      - name: Run UI Tests
        run: npm run test:ui:ci
        if: always()
